#services:
#  mysql:
#    image: mysql
#    ports:
#      - "3307:3307"
#    expose:
#      - "3307"
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
#      - MYSQL_DATABASE=mydb
#      - MYSQL_ROOT_PASSWORD=root